### ISSUE TITLE
Przeprowadzenie symulacji

### ISSUE THREAD

**Issue by rafalkrol100** [rafalkrol100/praca_magisterska#19]

**Comment by Coutonique** [comment]
lteHelper->SetPathlossModelAttribute("Exponent", DoubleValue(3.9));
    lteHelper->SetPathlossModelAttribute("ReferenceLoss", DoubleValue(38.57)); // ref. loss in dB at 1m for 2.025GHz
    lteHelper->SetPathlossModelAttribute("ReferenceDistance", DoubleValue(1));
//wartość exponenty wynika z warunków środowiskowych (dense urban area)
