### ISSUE TITLE
Spotkanie z promotorem 1 czerwca

### ISSUE THREAD

**Issue by Coutonique** [rafalkrol100/praca_magisterska#41]
Porozmawiać o kwestii konfigurowalności ilości RB na stacji bazowej

Parametry komórki: zapytać o promień komórki, ogólnie zapytać o inne parametry na przykład o moc stacji bazowej
Wspomnieć o wynikach z MIMO (300 UE, 7 eNB), czy nie przesadzone proporcje
MIMO w obliczeniach do algorytmu rezerwacji zasobów
Modulacja

Lista parametrów obecnie w symulacji:
Liczba UE (na komórkę)     **myslimy ze okolo 20**
Liczba stacji
Promień komórki **traktujemy promień jako zmienną 60m - 20 m krok i lecimy az krancowi sie wywalą**

Config::SetDefault("ns3::LteUePowerControl::Pcmin", DoubleValue(23.0)); **0dbm**
Config::SetDefault("ns3::LteUePowerControl::Pcmax", DoubleValue(23.0)); **33dbm zobaczyc powerheadroom**
lteHelper->SetEnbDeviceAttribute("UlBandwidth", UintegerValue(50));
lteHelper->SetEnbDeviceAttribute("Mtu", UintegerValue(1500));
lteHelper->SetUeDeviceAttribute("Mtu", UintegerValue(1500));
 
lteHelper->SetPathlossModelType(TypeId::LookupByName("ns3::LogDistancePropagationLossModel"));
lteHelper->SetPathlossModelAttribute("Exponent", DoubleValue(3.9));
lteHelper->SetPathlossModelAttribute("ReferenceLoss", DoubleValue(38.57)); // ref. loss in dB at 1m for 2.025GHz
lteHelper->SetPathlossModelAttribute("ReferenceDistance", DoubleValue(1));

Fading Trace
Obciążanie sieci (ilość pakietów czy radio) **wrzucic z inzyniera**

// set up strict frequency reuse model
lteHelper->SetFfrAlgorithmType("ns3::LteFrStrictAlgorithm");
lteHelper->SetFfrAlgorithmAttribute("DlCommonSubBandwidth", UintegerValue(6)); **sprawdzic istniejace implementacje albo zaufac wlasnemu sumieniu**
lteHelper->SetFfrAlgorithmAttribute("UlCommonSubBandwidth", UintegerValue(6));
lteHelper->SetFfrAlgorithmAttribute("DlEdgeSubBandOffset", UintegerValue(6));
lteHelper->SetFfrAlgorithmAttribute("DlEdgeSubBandwidth", UintegerValue(6));
lteHelper->SetFfrAlgorithmAttribute("UlEdgeSubBandOffset", UintegerValue(6));
lteHelper->SetFfrAlgorithmAttribute("UlEdgeSubBandwidth", UintegerValue(6));
https://www.nsnam.org/docs/models/html/lte-user.html#strict-frequency-reuse-algorithm

lteHelper->SetEnbAntennaModelType(antennaModel);
lteHelper->SetEnbAntennaModelAttribute("MaxGain", DoubleValue(maxGain)); **do ustalenia z kierunkowościa**

// ns3::LteFrStrictAlgorithm works with Absolute Mode Uplink Power Control
Config::SetDefault("ns3::LteUePowerControl::AccumulationEnabled", BooleanValue(false));

//w kontekście ilości przepięć
ueMobility.SetMobilityModel("ns3::RandomWalk2dMobilityModel",
                            "Mode", StringValue("Time"),
                            "Time", StringValue("2s"), **czas wyd;luza,my i zwiekszamy predkosc**
                            "Speed", StringValue("ns3::ConstantRandomVariable[Constant=1.0]"),
                            "Bounds", StringValue(bounds));

https://www.nsnam.org/docs/release/3.32/doxygen/classns3_1_1_lte_helper.html

**Comment by rafalkrol100** [comment]
przegadać koncepcje puszczania symulacji

**Comment by rafalkrol100** [comment]
sprawnosc widmowa w modelu teoretycznym powinna być brana z wzoru shannona i ewentualnych statystycznych odchylen od tego wzoru dla danego typu sieci

**Comment by rafalkrol100** [comment]
pogrubione komentarze należy przepisać do kodu. task zostawiam w statusie in progress i podpinam milestone na puszczanie symulek (de facto to ustawienie parametrów symulacji a logika jest gotowa).
